### ISSUE TITLE
Login requires email

### ISSUE THREAD

**Issue by Jordy281** [samchurney/teacherspet#1] opened 2015-11-03 21:30 UTC
when logging in as admin, it comes back with an error requiring an email. (For some people)

**Comment by samchurney** [comment] 2015-11-03 22:52
Ok, I figured out why this is happening.

I *did* change it to take the username instead of the email for logging in, however that change was made in this file:

`/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php`.

The problem is that this file is part of what gets installed with the `composer install` command so it isn't actually committed to the repository.

The fix will be to make the change somewhere outside of this file. 

I'll look for a solution.

**Comment by samchurney** [comment] 2015-11-03 23:18
Ok, made the change – just had to move the method that allowed username log in to the `AuthController`.

![Fist pump](https://media.giphy.com/media/14Xx5B178hibS/giphy.gif)

**Closed** 2015-11-03 23:18 UTC

**Comment by baderk** [comment] 2015-11-03 23:23
Haha awesome!

**Comment by samchurney** [comment] 2015-11-04 23:40
Ok. This should \*hopefully\* be resolved now as of c12e916fae87724540c178acbff56de3e310bef0
